### ISSUE TITLE
Hey there Owyn!

### ISSUE THREAD

**Issue by Shippou5** [Owyn/HandyImage#265]
I couldn't find you on essential mana anymore since the forums were taken down and I couldn't communicate with you there, I wanted to ask for help with your old tera boss hp bar mod, it broke in the new patch since the health number of bosses is just so high, my guildmates have enjoyed your work for the longest time and I couldn't find a way to help them with this issue so I thought that perhaps you could figure something out.

If this is the wrong place to speak these things out then I am active on discord, thank you from advance.

**Comment by Owyn** [comment]
bossbar was updated yesterday

https://www.undertow.club/threads/owyns-tera-ui-mods-elin-gunner-update.11709/ 

if it goes down the link to current thread (or original RU one which is always there with additional stuff) is in the pastebin at the top https://pastebin.com/8KgDhWbm

**Comment by Shippou5** [comment]
Thank you! I’ve left a like and a reply on the English thread, glad to see it back around :D

Regards,
Jacky Mary
050-9910992
