### ISSUE TITLE
imgur doesnt like direct linking

### ISSUE THREAD

**Issue by zosoro** [Owyn/HandyImage#268]
can something be done about fixing this? removing the refferal from the header?

**Comment by Owyn** [comment]
works fine for me https://imgur.com/wmrmO11

**Comment by zosoro** [comment]
try this https://i.imgur.com/wmrmO11.jpg

**Comment by Owyn** [comment]
script doesn't run on that page, it's just an image, and it works fine btw, check your other extensions
