### ISSUE TITLE
fix pzy.be 

### ISSUE THREAD

**Issue by swathigrate** [Owyn/HandyImage#269]
hello sir ,
i'm facing  small problem ..  pzy.be  is not working       fix it
thank you 
https://pzy.be/v/2/IMG_20171212_130404
https://pzy.be/v/2/IMG_20171212_130438
https://pzy.be/v/2/IMG_20171212_130447
https://pzy.be/v/2/IMG_20171212_130442
https://pzy.be/v/2/IMG_20171212_130435

**Comment by Owyn** [comment]
fixed https://github.com/Owyn/HandyImage/commit/acc11f6b8cf217637f55ca3ee7227189fc4df858
