### ISSUE TITLE
Sorry, for a dumb question

### ISSUE THREAD

**Issue by hemlok89** [Owyn/HandyImage#279]
I am asking a really noob question. I read the detail in greasyfork. But even after installing this script I see no changes in some supported image hosting sites. I tries instagram, imgur, photobucket. When I try to configure the script, this window pops up. 
![image](https://user-images.githubusercontent.com/39864104/46735970-6a567d00-ccb5-11e8-9c4e-523cc9b784c3.png)

**Comment by hemlok89** [comment]
I am using the latest version of Tampermonkey. But it is not being detected in instagram or flickr. 

![image](https://user-images.githubusercontent.com/39864104/46804063-5a0ad480-cd7f-11e8-9a95-989e82e7b1a0.png)
![image](https://user-images.githubusercontent.com/39864104/46804131-79096680-cd7f-11e8-8826-2cc20325c264.png)

The script is installed & activated

![image](https://user-images.githubusercontent.com/39864104/46804146-80307480-cd7f-11e8-8101-a107c4792932.png)

**Comment by Owyn** [comment]
I still see no example links

script doesn't run purposely on above images, it only runs on pages with single image which has an address of 
`https://*.instagram.com/p/*`
