### ISSUE TITLE
Flickr broken?

### ISSUE THREAD

**Issue by Jackie78De** [Owyn/HandyImage#302]
When I open a Flickr-image (ricght-click -> open in new tab) in Firefox, instead of an image I get an ampty website. This is happening since a few days. When I disable all the flickr-related entries in the userscript, I get the default Flickr view, but I would prefer only the one picture in fullscreen. Can anybody reproduce this?

**Comment by Owyn** [comment]
I could try reproducing it, if you gave an example link

**Comment by sysadminstory** [comment]
For example :
https://www.flickr.com/photos/kimjaneonflickr/12090171424/

**Comment by Owyn** [comment]
fixed
