### ISSUE TITLE
add/fix trans.firm.in

### ISSUE THREAD

**Issue by osteoblast22** [Owyn/HandyImage#321]
sample: http://trans.firm.in/images/2019/04/sm8i9nrdho3lvo3xbeo2.jpg.html
---
<sub>posted by [HandyImage-feedback](https://github.com/osteoblast22/HandyImage-feedback)</sub>

**Comment by osteoblast22** [comment]
@Owyn for some sites like the above there is no need to load the page and parse the image element, the image link can be parsed from the age URL, so for the above link you only need to remove the `.html` at the end, so redirecting the browser directly would be better.

**Comment by Owyn** [comment]
added
