### ISSUE TITLE
ADD: picusha.net

### ISSUE THREAD

**Issue by levicki** [Owyn/HandyImage#343]
Example URL:
https://picusha.net/?v=2018-05-09_gug40bdv3krtwxqeq1923cv81.jpg

Actual image URL for this example URL:
https://picusha.net/img/2018-05/09/gug40bdv3krtwxqeq1923cv81.jpg

I guess one way would be to rewrite using regex:

`var img = uri.replace(/^(.*)\?v=(\d{4}\-\d{2})\-(\d{2})_(.*)$/i, '$1img/$2/$3/$4');`

However I am not sure how to prevent the site from loading that animated "desktop girl" overlay ad which wastes bandwidth and slows down picture loading.

**Comment by Owyn** [comment]
added

+ you might want to use an ADblocker anyway to save bandwith etc

**Comment by levicki** [comment]
Thanks!

By the way I am using uBlock Origin and uMatrix but that animated ad is still playing. I guess no one bothered to add it to filter lists.

**Comment by LightGrey** [comment]
> Thanks!
> 
> By the way I am using uBlock Origin and uMatrix but that animated ad is still playing. I guess no one bothered to add it to filter lists.

You have to add "AdGuard Base List" filter in filter list if not there add this manually
/\/t[a-f0-9]{10,13}\.js$/$domain=erowall.com|adultwalls.com|motaen.com|camclips.cc|camwhores.biz|freeporn-site.com|imageteam.org|cambabe.video|cambabe.me|caminspector.net|free-strip-games.com|hdgirlstock.com|camwhores.tv|torrents-club.net|free-porn.games|picusha.net|porno-tracker.com|torrents-club.org|windows-soft.info|porno-island.games|zehnporn.com
