### ISSUE TITLE
fix instagram.com

### ISSUE THREAD

**Issue by Lambik** [Owyn/HandyImage#348]
Hi,

When going directly to a photo like on the url https://www.instagram.com/p/B8xG-Zon7rg/ I only see the instagram logo, and in the console I see the message "Didnt find image, waited 16000 ms to try again."

When I disable this specific script (tampermonkey in chrome), the photo does load.

**Comment by Lambik** [comment]
Apparently it's not for every instagram page, like this one works https://www.instagram.com/p/B9jc6FejHPZ/

**Comment by Owyn** [comment]
This is intended behavior, link you've provided is a `gallery`... how would you expect the script to work there anyway? It can only display one image at a time
![изображение](https://user-images.githubusercontent.com/1309656/76340328-74e2cf00-630c-11ea-9564-5dfef240864b.png)

![изображение](https://user-images.githubusercontent.com/1309656/76340351-81672780-630c-11ea-9dad-1aeae47d95ea.png)

**Comment by Lambik** [comment]
Well, could it just show the regular instagram page instead of the nothingness I get now?

![chrome_200311_101717989](https://user-images.githubusercontent.com/467373/76401057-99c55980-6381-11ea-9ca6-4460ef164950.png)

**Comment by Owyn** [comment]
I've shown you my screens above of how it works for me both in firefox and chrome, so make sure you don't have other userscripts \ extensions running which do this kind of screw up for the script

![изображение](https://user-images.githubusercontent.com/1309656/76402171-16613380-6394-11ea-8361-f17e349d4087.png)

**Comment by Lambik** [comment]
Hm, bizarre.

I tried this in an incognito window, both with no extensions enabled, and it works:

![chrome_200311_110443409](https://user-images.githubusercontent.com/467373/76405480-794ccd80-6388-11ea-8a0d-7b39dd11662a.png)

Then I enabled just this extension, and the original page threw an exception...:

![chrome_200311_110512491](https://user-images.githubusercontent.com/467373/76405524-8c5f9d80-6388-11ea-8722-aff7f3b868d8.png)

And it works at your end, which is even more weird :-)

Can I do something on my end to help debugging?

**Comment by Owyn** [comment]
Try newest version, maybe it has changed something for you

Else I could suggest launching a new clean firefox profile from `about:profiles` and seeing how it goes there if you were using Firefox, but in Chrome - no idea, and the userscript shouldn't change anything on the page **before** it finds an image, so 🤷‍♀

**Comment by Lambik** [comment]
I tried in a new chrome user setting, so without any extensions. Installed tampermonkey, and the newest version of HandyImage, and it does appear to work:

![chrome_200311_114826415](https://user-images.githubusercontent.com/467373/76409190-59200d00-638e-11ea-967c-30052722b290.png)

However, with the userscript enabled, I do still have the console error about loading the url with comma.

So there is something going on, somehow :-) But I will have to investigate on my own if there is a conflict with another script or extension, since it does work on a clean setting. I will report back with what I find...
