### ISSUE TITLE
Replace "return false;" with "quit ();"

### ISSUE THREAD

**Issue by SMylk** [Owyn/HandyImage#349]
The original is throwing all kind of errors on [FireMonkey ](https://addons.mozilla.org/en-US/firefox/addon/firemonkey/) cause it's not inside a function.

**Comment by Owyn** [comment]
` ReferenceError: quit is not defined` 🤷‍♂ 

Just write to firemonkey devs to fix their problem with `return`, cuz it works fine in all others...
