### ISSUE TITLE
Latest update broke imgur

### ISSUE THREAD

**Issue by alexolog** [Owyn/HandyImage#351]
Trying to open a direct imgur image results in an blank page.

The console says:
```
handy isn't needed for directly opened images  Handy_Image.user.js:797:2
http channel Listener OnDataAvailable contract violation
```

**Comment by Owyn** [comment]
works fine for me 
![изображение](https://user-images.githubusercontent.com/1309656/80079384-e4c5b580-8558-11ea-9481-b1580c4b451f.png)

plus if it says it isn't needed - that means it doesn't run and doesn't do anything at all...
