### ISSUE TITLE
fix imgbaron.com

### ISSUE THREAD

**Issue by ircopdd** [Owyn/HandyImage#353]
https://imgbaron.com/cu8g8sl0h2o5/ABPN-004.jpg.html
https://imgbaron.com/5dkwkf5lsmc7/ABPN-004_s.jpg.html

Google Chrome will display error on crash pages

**Comment by Owyn** [comment]
Yea, can confirm with my chrome too

Apparently it's crashing for lots of people in this month for lots of reasons https://support.google.com/chrome/thread/39056407?hl=en

I can only suggest you either switching to Firefox or adding imgbarom website to the exclusion list in your script manager (tampermonkey) (if it crashes only there)

**Comment by nindogo** [comment]
Hi,

I have just tried this on my Google Chrome (`Version 81.0.4044.138 (Official Build) (64-bit)`) and running the latest Tampermonkey(`Version 4.10`) running on Windows 10. It seems to work (even when I disable uBlock Origin on the site.

**Comment by ircopdd** [comment]
> Hi,
> 
> I have just tried this on my Google Chrome (`Version 81.0.4044.138 (Official Build) (64-bit)`) and running the latest Tampermonkey(`Version 4.10`) running on Windows 10. It seems to work (even when I disable uBlock Origin on the site.

Is it working
