### ISSUE TITLE
Todays update broke the script

### ISSUE THREAD

**Issue by Derwol** [Owyn/HandyImage#354]
Doesn't work anymore on all sites I tried. Trying to open the config page opens a blank page.

**Comment by Owyn** [comment]
After the update I tested it both in Firefox and Chrome (with TamperMonkey)

perhaps your configuration is different? or other extensions interfere?

check browser console for error messages (ctrl+shift+j)

**Comment by eks28** [comment]
Same here I just tried latest update (as of 6PM CST and all image pages your script supports blank I cant provide more info cause thats what happens

so I went back to this version (yesterday ver) and works fine https://github.com/Owyn/HandyImage/blob/e7ec26b02a2e4cb0958848d58f3e142bb0cc054d/HandyImage.user.js

**Comment by Owyn** [comment]
Yea, there was a big update - when pages get blank - perhaps some error can tell the details (press ctrl+shift+j to see the error console)

Are you using some rare script manager other than TamperMonkey or GreaseMonkey4?

**Comment by eks28** [comment]
Works now latest update thnx so mcuh love the script have been for awhile now A+
