### ISSUE TITLE
Configuration button not working?

### ISSUE THREAD

**Issue by JoeYunka** [Owyn/HandyImage#355]
When I press the configuration button it literally does nothing

**Comment by Owyn** [comment]
what's your script manager? works here in tampermonkey

**Comment by Owyn** [comment]
I tested it both in firefox and chrome with it and it worked

both when pressing "p" button and from extension drop-down menu

check browser console ctrl+shift+j for errors

or try disabling other extensions usescripts which may interfere

**Comment by JoeYunka** [comment]
apparently "p" works but the configuration button itself does not. i'll just use p instead.

thanks
