### ISSUE TITLE
Fix for GM3

### ISSUE THREAD

**Issue by alexolog** [Owyn/HandyImage#357]
Please change `GM = {};` in line 2855 to `window.GM = {};` to avoid the "assignment to undeclared variable GM" error and a resulting blank page.

Thank you!

**Comment by Owyn** [comment]
Saw that, it's already `var GM = {};` there now - should work

**Comment by alexolog** [comment]
I found other projects that dealt with the same problem.  There were reports that just adding `var` makes things break.

https://github.com/SOBotics/QueenReporter/issues/9

**Comment by Owyn** [comment]
Ok, used `window.GM` there now, hope it helps.
