### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by eks28** [Owyn/HandyImage#360]
I can install the latest 2 scripts (as of 5pm CST MAY 19th) using waterfox (firefox fork) or latest firefox latest greasemonkey (just installed latest ffox to see if waterfox issue and no problem on latest too)

all i get is parse error.other see screenshow 
<img width="491" alt="FFOX" src="https://user-images.githubusercontent.com/65427894/82385082-e323cc00-99f6-11ea-9473-e61fad8681e1.png">

**Comment by Owyn** [comment]
should be fixed now
