### ISSUE TITLE
add imgrock.pw, imgrock.net

### ISSUE THREAD

**Issue by anon-420** [Owyn/HandyImage#363]
sample:
https://imgrock.pw/HtOlnyVZoNY1NO-Lg8dGmpt9J23G-yFeFw.php
actual image:
https://r01.imgrock.net/img/znyfjeir7u7zsiew6ql5iu4oegvnj4a5mo3vpfvk2y/ymama02p.jpg

**Comment by Owyn** [comment]
fixed imgrock.pw
