### ISSUE TITLE
fix www.imgflare.com www.imgbabes.com

### ISSUE THREAD

**Issue by ircopdd** [Owyn/HandyImage#364]
https://www.imgflare.com/f/3snpe5016zy/1592901393.94.jpg.html
https://www.imgflare.com/f/u6xnu21wz8jn/FC2-PPV-1413177_s.jpg.html

https://www.imgbabes.com/f/7zvfh6yjmdtt/SIM-080_s.jpg.html
https://www.imgbabes.com/f/7zsfe4tmji48w24/EBOD-754_s.jpg.html

thanks

**Comment by Owyn** [comment]
fixed
