### ISSUE TITLE
Rewriting of `document` breaks other scripts and/or config

### ISSUE THREAD

**Issue by tophf** [Owyn/HandyImage#367]
As observed in Tampermonkey and Violentmonkey, when HandyImage rewrites `document` via document.write it breaks both HandyImage config (in userscript manager popup) and all userscripts that are injected after HandyImage and sometimes those that ran earlier. When rewriting via document.implementation the config survives but not the other userscripts.

Thing is, although Violentmonkey/Tampermonkey could easily detect this and re-inject other scripts, but there'll be a problem anyway as those scripts that already ran before HandyImage may have added events on `document` (this is a very common thing), they may have initialized some other internal things so re-running them would cause bugs.

Is there another method HandyImage could use?

**Comment by Owyn** [comment]
Yea, that's the point - to clear everything including everything attached to it and leave only HandyImage to fight invasive ads on ads-plagued websites

It does that only when image is found anyway and HandyImage leaves just the image and its controls

You can still access HandyImage settings via `P` Hotkey

**Comment by tophf** [comment]
Yeah, I forgot about ads as I usually don't see them, and image hostings are indeed one of the worst. I guess there's no reliable method, otherwise ad blockers wouldn't have to be so complex :-)
