### ISSUE TITLE
Wrong image displayed on xhamster

### ISSUE THREAD

**Issue by LurkerHub** [Owyn/HandyImage#369]
Note: I tried to find a SFW image for the example, but the site itself is NSFW.

https://xhamster.desi/photos/gallery/11033576/237235967
https://xhamster.com/photos/gallery/11033576/237235967

**Comment by Owyn** [comment]
Now should work fine

**Comment by LurkerHub** [comment]
Not working for other TLDs:

https://it.xhamster.com/photos/gallery/11033576/237235967

**Comment by Owyn** [comment]
now should be fixed

**Comment by LurkerHub** [comment]
Still issues with xhamster: 2nd and following pages of a gallery are treated as single images.

1st page of gallery is OK: https://xhamster.desi/photos/gallery/sfw-babes-hot-14419531
2st page of gallery is not OK: https://xhamster.desi/photos/gallery/sfw-babes-hot-14419531/2

**Comment by Owyn** [comment]
should now exclude pages with 1 to 3 numbers at the end so 1-999 pages should work

**Comment by alexolog** [comment]
:+1:
