### ISSUE TITLE
sankakucomplex causes uncontrolled memory growth [NSFW]

### ISSUE THREAD

**Issue by LurkerHub** [Owyn/HandyImage#370]
https://chan.sankakucomplex.com/post/show/5217282

Memory starts growing uncontrollably until the tab is closed.
No problem when https://chan.sankakucomplex.com/* is excluded

**Comment by Owyn** [comment]
Try it on an image which isn't a 50gm .gif file

Works fine for me in my firefox btw, my cpu is E6550 intel core 2 duo:
![изображение](https://user-images.githubusercontent.com/1309656/94963055-3149ef80-0500-11eb-9c2e-64e44f62d4ad.png)

**Comment by LurkerHub** [comment]
Can't seem to be able to reproduce it.  Closing.
