### ISSUE TITLE
Can't update script in Pale Moon

### ISSUE THREAD

**Issue by psonnosp** [Owyn/HandyImage#371]
I have the 2019.04.10 version of the script installed through Greasemonkey and when i clik the update button for the script nothing happens.
So tried installing it again from sleazyfork but when I click it this message is the only thing that happens
![Untitled-1](https://user-images.githubusercontent.com/28609335/95813809-068a4300-0d19-11eb-95a5-b49f7d1689b7.png)
 
I don't remember if I did something special to make it work the first time or not but is it possible to make the latest version of the script work with Pale Moon and Greasemonkey?

**Comment by Owyn** [comment]
Make sure you're using latest GreaseMonkey https://addons.mozilla.org/ru/firefox/addon/greasemonkey/ (works for me with it)

cuz if you're getting those errors it means your script manager is missing vital functions needed by this script (wildcard matching)

**Comment by psonnosp** [comment]
Pale Moon can't use the official version but an abandoned (?)[fork](https://github.com/janekptacijarabaci/greasemonkey/releases/tag/3.31.4Fork) based on 3.11 I think so that's a no go I'm afraid.
What version after 2019.04.10 is the last one not requiring wildcard matching?
Hopefully it'll atleast work on imagebam and a few others...

**Comment by psonnosp** [comment]
No it doesn't,  that GM fork is the only one.

So there are no versions of the script after 19.04.10 that doesn't have the wildcard matching thing?

**Comment by Owyn** [comment]
There aren't, I can only recommend considering using a more modern browser sadly.
