### ISSUE TITLE
chan.sankakucomplex.com not working with all images

### ISSUE THREAD

**Issue by JoeYunka** [Owyn/HandyImage#373]
most images on this website will give me a default sankakucomplex logo and not the image

**Comment by Owyn** [comment]
Example links? Cuz it works fine for me on every picture, even with ublock and all other scripts disabled

**Comment by JoeYunka** [comment]
The problem is definitely my browser, as it works on a different browser but I'm struggling to figure out how to fix it. I've tried disabling all other extensions and scripts but that didn't work. I tried clearing my browsing data which didn't work, then I tried changing a setting to allow all cookies (apparently it was set to block third-party cookies in incognito) and that did fix it at first, but then when I restarted my browser it stopped working again (and yes, the setting was still set to allow all), if there's anything else you can think of trying I'm all ears.

**Comment by Owyn** [comment]
Make sure you have latest version of the script installed

and you could press 'R' hotkey to show the original page when the problem occurs and inspect its content to see and screenhot both elemts it finds when you search for `a[itemprop="contentUrl"]` like this (press anywhere on the page with right mouse and 'inspect'):
![изображение](https://user-images.githubusercontent.com/1309656/96310551-477fa180-1010-11eb-845d-9991b1f50896.png)

**Comment by JoeYunka** [comment]
This good?

![ss (2020-10-16 at 08 17 45)](https://user-images.githubusercontent.com/65358091/96323851-dbd80d00-0fec-11eb-84ce-33c38b453a02.jpg)

**Comment by Owyn** [comment]
no, cuz if that's the only `a[itemprop="contentUrl"] ` element it finds - there can't be a problem

**Comment by JoeYunka** [comment]
I think it does have some sort of no-hotlinking protection. It's gotta be some setting with this browser that I just can't figure out. I've been using numerous other websites without any issues at all. I also tried restoring my chrome settings to their original defaults but that also didn't work, but I can deal with using a different browser for this website. Thank you
