### ISSUE TITLE
imgweng.xyz  same  imgxx.xyz

### ISSUE THREAD

**Issue by mahaicool** [Owyn/HandyImage#375]
after jump page, but not show any image

but the inspector can see the script is with image link is from "prcf.fiyar.live"
if(location.hostname == "www.venpix.xyz"){if(document.getElementById("tongkatlol") == undefined){
	document.location.href="https://prcf.fiyar.live/data_server_new/915/big/aaaaaaaaaaaaaaaaa.jpg";}}

**Comment by Owyn** [comment]
Added `imgweng.xyz`. See if updated version works on it, I can't check cuz you didn't give an example link

**Comment by mahaicool** [comment]
> 
> 
> Added `imgweng.xyz`. See if updated version works on it, I can't check cuz you didn't give an example link

this is example link
http://imgblaze.net/2dcsxlf

**Comment by Owyn** [comment]
Example link works fine for me: 
![изображение](https://user-images.githubusercontent.com/1309656/97321547-0c873480-1880-11eb-92b6-cb20838eac4e.png)
