### ISSUE TITLE
Fix (2)

### ISSUE THREAD

**Issue by TiniestCupcake** [Owyn/HandyImage#377]
https://imgoutlet.pw/RlUt4zdUBfTa3V1dwNBejrNgiAqxLdhb1w.php
to
https://io1.imgoutlet.com/img/vtgnpnbutrcxa3oeh3qjyecjonaoegwexcdln6mfea/ug475fthy27m_zz.jpg
--Does nothing, but I saw it listed. Let me know if you need more examples.

https://imgtown.pw/f-PSE5a0Bvu38Xjovcz8cXo2gu9VPyWYGg.php
to
https://it1.imgtown.net/img/znybgg3n7vxyul6g54kimbe7gbvpldlcz4dts2nx6q/7pf5oaedypc0_zz.jpg
--Same

**Comment by Owyn** [comment]
Says "File Not Found" on both links, no images there

**Comment by TiniestCupcake** [comment]
Just tried it out, seems it doesn't allow going directly to the image from the link, only though clicking through the base link. I can still get to the images through the first link for each (but I have to click a bunch of times).

**Comment by Owyn** [comment]
should work now
