### ISSUE TITLE
Imagefap Help.

### ISSUE THREAD

**Issue by junomarian** [Owyn/HandyImage#383]
Hi Dev, 
NSFW
So here in imagefap page

https://www.imagefap. dot com/pictures/8993374/Manga-sexfight-III

When i click on particular picture thumbnail it takes me to next page , But I want to open full sized image directly clicking on these thumbnails instead going to next page. Any modifications i can make, 
Example https://www.imagefap.com/pictures/*

**Comment by Owyn** [comment]
Works fine for me: 
![изображение](https://user-images.githubusercontent.com/1309656/100540142-782c3b00-324c-11eb-9ac0-bac6405bdfc7.png)

Make sure the script is installed and on

**Comment by junomarian** [comment]
> Works fine for me:
> ![изображение](https://user-images.githubusercontent.com/1309656/100540142-782c3b00-324c-11eb-9ac0-bac6405bdfc7.png)
> 
> Make sure the script is installed and on

Thanks for your reply,
I am on Android phone.
Fennec F-Droid Browser 68.12.0
Tampermonkey 4.11.6120
Same link page is opened but tamper monkey says no script running.

**Comment by Owyn** [comment]
Make sure that the userscript is installed ?

If it is, check page url address - perhaps it's slightly different that's why it won't run there

**Comment by junomarian** [comment]
> Make sure that the userscript is installed ?
> 
> If it is, check page url address - perhaps it's slightly different that's why it won't run there

Yes, it will definitely work on PC. i will use it their. 
You can close this issue.
