### ISSUE TITLE
add/fix imgprime.com

### ISSUE THREAD

**Issue by osteoblast22** [Owyn/HandyImage#386]
sample: https://imgprime.com/imgb-u/b/2019/05/29/5cee7c98de379.jpeg.html
---
<sub>posted by [HandyImage-feedback](https://github.com/osteoblast22/HandyImage-feedback)</sub>

**Comment by Owyn** [comment]
works fine for me

Check without other extensions & userscripts

**Comment by Owyn** [comment]
checked again, now stopped working for my stable firefox as well, no idea why

@osteoblast22 do you have uBlock extension? try turning it off

after I turned it off for the site it started working again

it's breaking somewhere in the TM wrapper I think  btw @derjanb 

![изображение](https://user-images.githubusercontent.com/1309656/102147275-8cdb1680-3e7b-11eb-8ca2-d4ce79a28f5e.png)

**Comment by derjanb** [comment]
@Owyn I'll check this...

**Comment by elvisef** [comment]
> 
> ## sample: https://imgprime.com/imgb-u/b/2019/05/29/5cee7c98de379.jpeg.html
> 
> posted by [HandyImage-feedback](https://github.com/osteoblast22/HandyImage-feedback)

It works for me.

**Comment by derjanb** [comment]
@Owyn document.createElement is overwritten by uBlock and there is not much Tampermonkey can do. However [GM_addElement](https://github.com/Tampermonkey/tampermonkey/issues/881#issuecomment-639705679) should still work.

**Comment by osteoblast22** [comment]
I can confirm that turning ublock off fix the problem

**Comment by tophf** [comment]
> document.createElement is overwritten by uBlock

FWIW, `Document.prototype.createElement.call(document, 'div')` should still work.

**Comment by Owyn** [comment]
https://github.com/Owyn/HandyImage/commit/dc71a5f75d453a64bdbffa1a240f04299e39b52d 

See if it helps, probably should, at least its still works fine as it was in FF & Chrome

**Comment by elvisef** [comment]
I've just installed the newest version of HandyImage now, i.e.: `2021.04.12` and it works like a charm.
Moreover, it works even with uBlock enabled. I've never had issues with this.
Maybe uBlock have some other, not standard entries @osteoblast22  ?

Version of uBlock, Firefox and OS:
![2021-04-27_07-54](https://user-images.githubusercontent.com/25976749/116192368-0b9b6680-a72e-11eb-97bd-bd375a3b93c2.png)
![2021-04-27_07-54_1](https://user-images.githubusercontent.com/25976749/116192371-0c33fd00-a72e-11eb-8748-e9a95f79a6ac.png)
![2021-04-27_07-54_2](https://user-images.githubusercontent.com/25976749/116192373-0ccc9380-a72e-11eb-8b7f-f394a80daa35.png)
