### ISSUE TITLE
not working on urlgalleries.net

### ISSUE THREAD

**Issue by junomarian** [Owyn/HandyImage#387]
NSFW https://dadi.urlgalleries.net/porn-gallery-7554847/3/Anjelica-I-See-You&a=100

How i can get direct image links on this gallery?
hidden behind go.urlgalleries.net gocash

**Comment by Owyn** [comment]
Images are hosted at fappic image hosting which works fine with the script, 
ulrgalliries is just a redirect link shortener site which does not host any images

if you want to skip ads or bypass em try something like https://github.com/adsbypasser/adsbypasser

**Comment by junomarian** [comment]
> Images are hosted at fappic image hosting which works fine with the script,
> ulrgalliries is just a redirect link shortener site which does not host any images
> 
> if you want to skip ads or bypass em try something like https://github.com/adsbypasser/adsbypasser
