### ISSUE TITLE
imgfrost_net does not show images

### ISSUE THREAD

**Issue by elvisef** [Owyn/HandyImage#390]
Hello.

I don't know if this is a server error, because after redirect, it loops over and over...

example link: `http://imgfrost.net/up4sbomg`

So it redirects to `https://imgweng.xyz/up4sbomg` and loops without ending.

Can You check this please ?

PS.Using MaxURL addon I checked it, and the big size image is available and is working.

**Comment by Owyn** [comment]
works fine for me

> So it redirects to https://imgweng.xyz/up4sbomg
it doesn't, it's your `https everywhere` doing, and since website supports only `http` it redirects to it, and then your extension redirects back to https

**Comment by elvisef** [comment]
I see what You mean, it's a loop. But I do not have any "https everywhere" addons installed. That's what You meant, an additional addon which makes redirect loops ?

**Comment by Owyn** [comment]
perhaps you have another extension similar to it, because normally it doesn't open https:// site version



After I turned off my https every extension it all worked fine in firefox + tampermonkey

try turning other extensions & userscripts off, if it doesn't help - what's your browser and script manager?

**Comment by elvisef** [comment]
I've just checked the link to "imgfrost" from my first post `(http://imgfrost.net/up4sbomg),` and now it redirects to another address: `http://imgair.net/up4sbomg` instead of `https://imgweng.xyz/up4sbomg`. So again, it asks for clicking after 5 seconds waiting to see an image.

Can You recheck it ?

**Comment by Owyn** [comment]
still redirects to imgweng for me: 
![изображение](https://user-images.githubusercontent.com/1309656/104015493-c32f5b80-51c5-11eb-965b-07b6545d3421.png)

imgair link redirects me to imgkes.xyz - added both to the script, now those should work too

**Comment by elvisef** [comment]
Updated the script i nmy FF. I've Checked this,but it works very weird:

1.`http://imgfrost.net/up4sbomg` redirects to `http://imgair.net/up4sbomg`
2.Then it counts from 5 to 0 seconds
3.Next, shows ads with "continue to image" on top
4.After waiting hmm... 2-3 seconds a direct image appears

I think something is wrong here. i've checked this on clean Firefox, with only TamperMonkey installed with HandyImage script.

PS.Https forced links may be due to ublock, ghostscript or duckduckgo addons. But here, in the clean FF, there is no other scripts, but it works a bit weird. In fact the time I am waiting for the image is the time I could click it earlier.

**Comment by Owyn** [comment]
If there is no button for script to press to skip to image... what do you expect script to do? hmmm...

**Comment by elvisef** [comment]
This is how it works on clean FF, with only TamperMonkley with HandyImage installed.

https://user-images.githubusercontent.com/25976749/104105009-b127e880-52ab-11eb-858b-f6612c0cd2b2.mp4

It's correct, yes ? : )
If Yes, I am closing issue.

I thought that I will be redirected automatically without any seconds waiting (without additional counters or buttons as for other sites/pages). That is why I asked about this to check. Maybe I misunderstood something.

**Comment by Owyn** [comment]
Yes, it's correct.

**Comment by elvisef** [comment]
Alright : )
