### ISSUE TITLE
Twitter is unusable... displays first image in a "thread"

### ISSUE THREAD

**Issue by nick-s-b** [Owyn/HandyImage#391]
Hi,

I've noticed that when I use HandyImage on Twitter, it just displays the first image it finds on the page. You cannot see the tweet or anything else on the page. You have to disable the script completely to actually see anything else. The image doesn't even have to be in the linked tweet... HI will full-screen the first image it finds on the page. I find this behavior worse than useless. Can it be modified or completely disabled for twitter?

Thanks Owyn!

**Comment by Owyn** [comment]
You're right,

disabled it for statuses in new version and now it'd only work for `/photo/` links
