### ISSUE TITLE
add/fix kvador.com

### ISSUE THREAD

**Issue by osteoblast22** [Owyn/HandyImage#394]
sample: https://kvador.com/np9co3dideni/traw.jpg.html
---
<sub>posted by [HandyImage-feedback](https://github.com/osteoblast22/HandyImage-feedback)</sub>

**Comment by Owyn** [comment]
works fine for me

**Comment by osteoblast22** [comment]
I think it's a another conflict with ublock, if I turn it off it works fine

**Comment by Owyn** [comment]
See if new version helps with the conflict, probably should, at least it still works fine as it was in FF & Chrome
