### ISSUE TITLE
fix imgur.com

### ISSUE THREAD

**Issue by spammity** [Owyn/HandyImage#400]
https://imgur.com/gallery/xrOet

Add:

// @exclude	*://imgur.com/gallery*
// @exclude	*://*.imgur.com/gallery*

**Comment by Owyn** [comment]
but why?

script already checks if it's a gallery to see if it should run (galleries also have other kinds of url e.g. `/a/`)

**Comment by spammity** [comment]
Sorry - my suggested fix wasn't a fix.

imgur.com pages are breaking in FF with HandyImage enabled with all other scripts are disabled. Getting a blank gray page with no content.

I'm getting the following errors:

`Uncaught Error: Permission denied to access object
    n https://s.imgur.com/desktop-assets/js/main.8ca5beb4ac2958954731.js:15
    mn https://s.imgur.com/desktop-assets/js/main.8ca5beb4ac2958954731.js:15
    start https://s.imgur.com/desktop-assets/js/main.8ca5beb4ac2958954731.js:15
    Efxr https://s.imgur.com/desktop-assets/js/main.8ca5beb4ac2958954731.js:15
    d https://s.imgur.com/desktop-assets/js/main.8ca5beb4ac2958954731.js:1
    13uX https://s.imgur.com/desktop-assets/js/main.8ca5beb4ac2958954731.js:1
    d https://s.imgur.com/desktop-assets/js/main.8ca5beb4ac2958954731.js:1
    0 https://s.imgur.com/desktop-assets/js/main.8ca5beb4ac2958954731.js:1
    d https://s.imgur.com/desktop-assets/js/main.8ca5beb4ac2958954731.js:1
    <anonymous> https://s.imgur.com/desktop-assets/js/main.8ca5beb4ac2958954731.js:1
    <anonymous> https://s.imgur.com/desktop-assets/js/main.8ca5beb4ac2958954731.js:1
main.8ca5beb4ac2958954731.js:15:22720

Uncaught Error: Permission denied to access object
    n https://secure.quantserve.com/quant.js:2
    <anonymous> https://secure.quantserve.com/quant.js:2
    require https://secure.quantserve.com/quant.js:2
    define https://secure.quantserve.com/quant.js:2
    <anonymous> https://secure.quantserve.com/quant.js:2
    <anonymous> https://secure.quantserve.com/quant.js:2
quant.js:2:2581


Uncaught Error: Permission denied to access object
    <anonymous> https://connect.facebook.net/en_US/fbevents.js:23
    <anonymous> https://connect.facebook.net/en_US/fbevents.js:23
    <anonymous> https://connect.facebook.net/en_US/fbevents.js:23
    getFbeventsModules https://connect.facebook.net/en_US/fbevents.js:23
    <anonymous> https://connect.facebook.net/en_US/fbevents.js:23
    <anonymous> https://connect.facebook.net/en_US/fbevents.js:23
    <anonymous> https://connect.facebook.net/en_US/fbevents.js:23
    getFbeventsModules https://connect.facebook.net/en_US/fbevents.js:23
    <anonymous> https://connect.facebook.net/en_US/fbevents.js:26
    <anonymous> https://connect.facebook.net/en_US/fbevents.js:26
    <anonymous> https://connect.facebook.net/en_US/fbevents.js:26
    getFbeventsModules https://connect.facebook.net/en_US/fbevents.js:23
    <anonymous> https://connect.facebook.net/en_US/fbevents.js:26
    <anonymous> https://connect.facebook.net/en_US/fbevents.js:26
    <anonymous> https://connect.facebook.net/en_US/fbevents.js:26
fbevents.js:23:52330
`

**Comment by spammity** [comment]
For reference, the following URLs behave differently when HandyImage is enabled, but have the same layout when disabled:

`https://imgur.com/a/K8m7p2t`

The above shows a blank gray page.

`https://imgur.com/4EkJaim`

This one does what I would expect - only the image is displayed at full size.

**Comment by spammity** [comment]
Originally installed HandyImage with GreaseMonkey. Just installed with TamperMonkey instead, and everything seems to be working swimmingly!
