### ISSUE TITLE
fix 500px.com

### ISSUE THREAD

**Issue by spammity** [Owyn/HandyImage#401]
https://500px.com/photo/1022302567/Below-the-surface-by-Chun-Chau/

**Comment by Owyn** [comment]
works for me, check other extensions aren't breaking things for you

![image](https://user-images.githubusercontent.com/1309656/108561947-27d6ed80-7310-11eb-82e7-5e45fbf395e1.png)

**Comment by spammity** [comment]
Originally installed HandyImage with GreaseMonkey. Just installed with TamperMonkey instead, and everything seems to be working swimmingly!
