### ISSUE TITLE
add/fix imgkoi.xyz

### ISSUE THREAD

**Issue by osteoblast22** [Owyn/HandyImage#403]
sample: http://imgkoi.xyz/kotiug
---
<sub>posted by [HandyImage-feedback](https://github.com/osteoblast22/HandyImage-feedback)</sub>

**Comment by Owyn** [comment]
website doesn't work in clean firefox, just keeps reloading forever, so can't add it

![image](https://user-images.githubusercontent.com/1309656/108721802-79ab8d80-7533-11eb-90b6-2e37d992a99d.png)

**Comment by Owyn** [comment]
Works fine, there's nothing to fix.
