### ISSUE TITLE
500px full resolution

### ISSUE THREAD

**Issue by spammity** [Owyn/HandyImage#404]
The following code loads images up for 4096px on the longest side:

`	case "500px.com":
		j = true;
		i = q('img.photo-show__img[src*="_m"]');
        if (i) {
            var m = i.src.match('/photo/(\\d+)/');
            if (m) {
                var xhttp = new XMLHttpRequest();
                xhttp.open('GET', 'https://api.500px.com/v1/photos?ids=' + m[1] + '&image_size=4096');
                xhttp.onload = function() {
                    if (xhttp.status == 200) {
                        try {
                            i.src = JSON.parse(xhttp.response)['photos'][m[1]]['images'][0]['url'];
                        } catch (e) {}
                    }
                }
                xhttp.send();
            }
        }
		break;
`
It works, but there's a lot of errors output to the console after HandyImage runs. I may not be using the HandyImage vars properly...

**Comment by Owyn** [comment]
Those errors are the same even before the new code for me, it's the website's JS which is doing it

Just tested - the hack indeed works for now, even for low res photos https://500px.com/photo/1028652868/Belle-by-Jovana-Rikalo/ 

added in https://github.com/Owyn/HandyImage/commit/10e1a8eab8a3221b608140cc0738a170eb870bcb
