### ISSUE TITLE
add picrok.com

### ISSUE THREAD

**Issue by anonymo0se** [Owyn/HandyImage#407]
Sample(nsfw):
https://picrok.com/xl_mGtTdnDpMTg7XnKHLva_SI5yY4mY7lA.php
Link to image(nsfw):
https://r01.imgrock.net/img/znyjkdaf7u3mu6my4ihyquose4vvha2khyh3zqkpim/FC2-PPV-1724167.jpg

**Comment by Owyn** [comment]
added
