### ISSUE TITLE
pixroute.com

### ISSUE THREAD

**Issue by eks28** [Owyn/HandyImage#416]
**Example links to pages with a single image to fullsize: **

- 
Can you fix https://pixroute.com

Example image (WARNING P0rn):

https://pixroute.com/0ee5gbwzhnly/_720hq.mp4_thumbs_[2021.05.02_14.41.35

thnx

**Comment by Owyn** [comment]
fixed, 
even though it seems someone just copied the link wrong cuz on that page it shows a working link on the bottom of the page
