### ISSUE TITLE
[Suggestion] - README page, unable to find installation instructions

### ISSUE THREAD

**Issue by slrslr** [Owyn/HandyImage#423]
Hello,
please what are the steps to install HandyImage, i am having Firefox 88.

I see there is a raw .js file: https://raw.githubusercontent.com/Owyn/HandyImage/master/HandyImage.user.js
but when i drag/drop it to the page about:addons
it says it may be corrupted

[The page](https://greasyfork.org/en/scripts/109-handy-image) linked in the project description seems to no longer display anything useful.

**Comment by Owyn** [comment]
you need a script manager to install userscripts, e.g. https://www.tampermonkey.net/

**Comment by slrslr** [comment]
thank you, i see that it is closed source, i have found open source:
https://violentmonkey.github.io/ (https://addons.mozilla.org/en-US/firefox/addon/violentmonkey)
#424 
and after submitting mentioned .js URL to this addon and reloading page, it started working, showing image directly without any other ads etc.. Thank you
