### ISSUE TITLE
support for a website

### ISSUE THREAD

**Issue by Kaorw** [Owyn/HandyImage#431]
**Example links to pages with a single image to fullsize: **

link of site
http://imgjut.buzz/kwkaf

fullsize img link
https://prcf.imgbig.xyz/data_server_new/5599/big/unnamed.jpg

**Comment by Owyn** [comment]
https://github.com/Owyn/HandyImage/commit/f9f5a82cab7f1e99517fe13d7d918403e0143e52 
added
