### ISSUE TITLE
[Suggestion] - imgur.com issue

### ISSUE THREAD

**Issue by x94fujo6rpg** [Owyn/HandyImage#438]
can you add
```
// @exclude		*://*.imgur.com/all*
```

this script will run & break the site when I need to check all my account images at `https://username.imgur.com/all`
`username` = user/account  name

![2021-07-26 11_50_14-firefox-logo png (64x66)](https://user-images.githubusercontent.com/14246119/126930743-c71f0052-8ae3-4540-b373-2be4c10ac9d6.png)

**Comment by Owyn** [comment]
added 👍🏻
