### ISSUE TITLE
add/fix fastpic.org

### ISSUE THREAD

**Issue by Rellec** [Owyn/HandyImage#439]
Sample: https://fastpic.org/view/115/2021/0728/_723e40992a40a26f6dc29675ac8bd3ec.png.html
Same as fastpic.ru

**Comment by Owyn** [comment]
added

**Comment by zubrRB** [comment]
Reference of this type: https://fastpic.org/fullview/117/2022/0412/cde9fa1eddef11a109775b347b52818c.png.html
