### ISSUE TITLE
postimg.cc/gallery is broken when HandyImage is enabled

### ISSUE THREAD

**Issue by slrslr** [Owyn/HandyImage#441]
Hello,

signup (or maybe just upload an image at https://postimg.cc/
then i go to the section/gallery to which i added the image https://postimg.cc/gallery/galleryaddress
then i put mouse cursor over image thumbnail, the trash bin icon appear but clicking it does not trigger the dialog window to confirm removal. When i disable HandyImage in my Violentmonkey Firefox extension, then it start showing.

// \@name		Handy Image
// \@version		2021.08.07

**Comment by Owyn** [comment]
should be fixed in latest version
