### ISSUE TITLE
fix servimg.com

### ISSUE THREAD

**Issue by zubrRB** [Owyn/HandyImage#443]
http://~www~ and https:
http://servimg.com/view/17653514/86
https://servimg.com/view/17653514/86

**Comment by Owyn** [comment]
there is no www or http address available, it just redirects to https one without www

**Comment by zubrRB** [comment]
`// @match	 	http://www.servimg.com/image*`

**Comment by Owyn** [comment]
fixed

**Comment by zubrRB** [comment]
`*://servimg.com/view/*`
