### ISSUE TITLE
add vfl.ru

### ISSUE THREAD

**Issue by zubrRB** [Owyn/HandyImage#444]
http://vfl.ru/fotos/a94a645533509277.html
https://vfl.ru/fotos/a94a645533509277.html

**Comment by Owyn** [comment]
http address doesn't work

**Comment by Owyn** [comment]
added

**Comment by zubrRB** [comment]
> http address doesn't work

Both addresses work for me. Maybe your browser or extension makes a forced redirect to HTTPS?

**Comment by Owyn** [comment]
No
![image](https://user-images.githubusercontent.com/1309656/130286596-6f126e44-9a28-49d8-96c7-e555b2085fbd.png)

**Comment by zubrRB** [comment]
This is due to the use of the Private Mode window in Firefox. In it, I also have a redirect to HTTPS.

**Comment by Owyn** [comment]
same in not private:
![image](https://user-images.githubusercontent.com/1309656/130314706-ea5129df-0d66-42ae-803a-79bc2857924e.png)

**Comment by zubrRB** [comment]
Do you have the opportunity to check in another browser?

**Comment by Owyn** [comment]
Chrome opens http fine for some reason

**Comment by zubrRB** [comment]
There is no forced redirect in Chrome or its extensions.
