### ISSUE TITLE
Centering images doesn't work in AdGuard

### ISSUE THREAD

**Issue by zubrRB** [Owyn/HandyImage#447]
Is there any way to improve the situation? https://radikal.ru/lfp/d.radikal.ru/d38/2108/e6/0e1e59985b1d.png/htm

<details><summary>Screenshot:</summary>

![1](https://user-images.githubusercontent.com/50718960/131259407-0b758368-7d78-4b92-b9b7-9622bc371353.png)
![2](https://user-images.githubusercontent.com/50718960/131259410-228a222c-ee03-492b-9929-8f29a46d3b2b.png)
![3](https://user-images.githubusercontent.com/50718960/131259413-33cdd11c-ec75-4d17-ab8d-f616990ea2fe.png)
</details><br/>

**Comment by Owyn** [comment]
You posted screenshots where it works perfectly

**Comment by zubrRB** [comment]
But initially, when opening, the image does not fit into the screen frame and climbs the right, as shown in the first screenshot. 
I have to additionally do two clicks.

**Comment by Owyn** [comment]
Check your settings

**Comment by zubrRB** [comment]
For some reason, at the very beginning, the images are not centered. Everyone, not just small ones. Equally in Chrome and Firefox.

**Comment by zubrRB** [comment]
Tampermonkey does not have this problem, everything is centered there. The problem is observed only in AdGuard.

**Comment by Owyn** [comment]
I have Tampermonkey and it looks exactly like on your screens, check your settings
tho if you are sure the problem is in AdGuard - you should contact its developers, because I can't see any problems

**Comment by zubrRB** [comment]
In version 2021.08.30, the image now opens correctly, but the sequence of screenshots has changed. 
The first became the third, that is, after the second click, the image climbs beyond the screen to the right. Albeit small in size.

**Comment by Owyn** [comment]
It has not changed, you just start from different stage now.

do you think the sequence should be different?

**Comment by zubrRB** [comment]
And why is a small image stretched at all, which climbs beyond the screen with a resolution of 1280x1024?

![skrin](https://user-images.githubusercontent.com/50718960/132090013-9454e296-4851-41d7-9c66-d832b9299d2d.png)

**Comment by Owyn** [comment]
because you either clicked it to stretch it or have it so in options on load?

**Comment by zubrRB** [comment]
Yes, on the second click. But why doesn't it fit into the screen?
After all, initially, when opened, it adjusts to the resolution of the monitor, and then climbs out. What's the point of this?

**Comment by Owyn** [comment]
The point is to fill image into screen
![image](https://user-images.githubusercontent.com/1309656/132090651-198c96d7-c7d7-4197-b8f7-a7eb9f278194.png) (first image result from google search "fill image")

most useful for long thin images about 50% of screen width for example you'd want to enlarge

**Comment by zubrRB** [comment]
Thanks for the clarification! And improved with centering on opening. Apparently, you can close it?
