### ISSUE TITLE
Add dewimg.com and pictwn.com

### ISSUE THREAD

**Issue by SweetLoli** [Owyn/HandyImage#449]
**Example links to pages with a single image to fullsize: **
NSFW
-https://dewimg.com/gs54ok3s71zb/0019.jpg.html
-https://tryimg.xyz/q2mhds87kcho/Ублажает_себя_2.avi.jpg.html

**Comment by Owyn** [comment]
added

**Comment by SweetLoli** [comment]
> added

pictwn.com can’t automatically skip "Continue to Image...", still need to click this button manually.

**Comment by Owyn** [comment]
> 
> 
> > added
> 
> pictwn.com can’t automatically skip "Continue to Image...", still need to click this button manually.

works fine for me both in firefox and chrome, try disabling other extensions which may interfere

**Comment by SweetLoli** [comment]
> > > added
> > 
> > 
> > [pictwn.com](http://pictwn.com) can’t automatically skip "Continue to Image...", still need to click this button manually.
> 
> works fine for me both in firefox and chrome, try disabling other extensions which may interfere

Oh, after I turned off the VPN proxy extensions on pictwn.com, it can now automatically skip "Continue to Image..."! Thank you. :D
