### ISSUE TITLE
support for a website ibb.co is not working

### ISSUE THREAD

**Issue by harisx** [Owyn/HandyImage#463]
**Example links to pages with a single image to fullsize: **
ibb.co is not working

https://ibb.co/Vws5J4L
-

**Comment by Owyn** [comment]
It's working for me 

![image](https://user-images.githubusercontent.com/1309656/146922922-4f5bf442-cef5-4616-bcb0-e1f30020ac9f.png)

try disabling your other extensions \ userscripts

**Comment by harisx** [comment]
got it, fixed after disabling Image Max userscripts.

thanks
