### ISSUE TITLE
fix: imgtaxi.com

### ISSUE THREAD

**Issue by King555** [Owyn/HandyImage#468]
When I activate the userscript I neither see the image nor the "Continue to image" link on imgtaxi.com. When I deactivate it, I see the link and I can click it.

Sample link: https://www.imgtaxi.com/img-552ad2bd0ddc8.html

**Comment by Owyn** [comment]
That's the point of the script - you don't have to click it, script does it... if you don't have other extensions to break it all together.

Disable other browsers extensions and see if it helps and which one breaks it. cuz it works fine for me here:
![изображение](https://user-images.githubusercontent.com/1309656/156921331-9caa5912-a232-4aa3-86ea-42298a57fa90.png)

**Comment by King555** [comment]
I know that the userscript should bypass the link I have to click. But when I activate it it does not only _not_ work, it also disables the link and I can't even manually open the image.

The only other extension I can think of is my ad-blocker (uBlock Origin), but I disabled it and it did not work either.

Only in the case you tested it first without the userscript, please note that after opening the image successfully once, any other openings of that link will directly go to the image, no matter whether there is any extension or not (at least this is what I experienced).

If the script really works flawlessly, do you have any other idea except other extensions?

**Comment by Owyn** [comment]
Firefox incognito: 
![изображение](https://user-images.githubusercontent.com/1309656/156921963-ebc60461-25ee-481a-847a-2cec2b833f0a.png)

Try seeing your browser console to see any useful info or errors (ctrl+shift+i)

**Comment by Owyn** [comment]
> If the script really works flawlessly, do you have any other idea except other extensions?

yea, Greasemonkey  is overall a very bad outdated abandoned by every user old extension - try TamperMonkey https://www.tampermonkey.net/

**Comment by King555** [comment]
Tampermonkey works, thank you!

The only messages in the console concerning your userscript said that an image could not be found and it will wait X ms. Other (error) messages were in scripts on imgtaxi.

For me the problem is solved, unless you need more infos to fix it for Greasemonkey.

**Comment by Owyn** [comment]
I'll look at Greasemonkey myself, but, I think there were even more things not working with it, so it doesn't matter much
