### ISSUE TITLE
[Suggestion] - pixiv.net rule is slow, and requires logging in

### ISSUE THREAD

**Issue by FlowerForWar** [Owyn/HandyImage#476]
I suggest this rule instead.
```
case 'pixiv.net':
	i = document.querySelector('meta[name="preload-data"]');
	if (i) {
		let a = JSON.parse(i.getAttribute('content')).illust;
		let b = a[Object.keys(a)[0]];
		if (b.pageCount !== 1) return;
		i.src = b.urls.original;
	}
	break;
```

**Comment by Owyn** [comment]
It won't work in the Chrome tho, cuz chrome doesn't support disabling javascript the way this userscript does

**Comment by Owyn** [comment]
and when there are multiple pages detected - site will be left broken cuz no javascript loaded

**Comment by Owyn** [comment]
Seem to works so far, let's see how it goes.
