### ISSUE TITLE
Add http://imguo.buzz/wxbnd

### ISSUE THREAD

**Issue by AltSanvas** [Owyn/HandyImage#487]
New Redirect. 

Thanks!

**Comment by Owyn** [comment]
example links?

**Comment by AltSanvas** [comment]
Apologies, original link is:
http://imgblaze.net/wxbnd

and redirects to:
http://imguo.buzz/wxbnd

Is imgblaze.net an issue?

**Comment by Owyn** [comment]
what issue?

script only works for sites specifically added to it

**Comment by Owyn** [comment]
added imguo.buzz
