### ISSUE TITLE
Disable AdBlock Splash Image Appearing with the usage of HandyImage script

### ISSUE THREAD

**Issue by AltSanvas** [Owyn/HandyImage#489]
![image](https://user-images.githubusercontent.com/109953109/181889460-d3fae695-6906-4e5d-a1d5-cc58617fe087.png)

I was working on a personal fork to see if I can add the image host, "http://imgkuz.buzz/lk8rqrwxq". I was successful in adding it but I came across a "disable AdBlock Image". I was playing around what causes it and the only thing triggering it was the script. With the script turned off the "disable Adblock image" would not appear.

**Comment by Owyn** [comment]
just throw the domain to the rest of buzz spammy domains - should work

> "disable AdBlock Image

so does the script catch the image to fullsize or not?

**Comment by AltSanvas** [comment]
> so does the script catch the image to fullsize or not?

It does.

**Comment by Owyn** [comment]
> > so does the script catch the image to fullsize or not?
> 
> It does.

so where does the adblock image pop up then? if image is fullsized - nothing else is there then 🤔

**Comment by AltSanvas** [comment]
Funnily enough the issue seems to have resolved itself. I am no longer getting the adblock image.
