### ISSUE TITLE
fix imx.to

### ISSUE THREAD

**Issue by BlondFace** [Owyn/HandyImage#491]
Clicking on a link will load the image in full size. The next click switches to full view, but after that no longer possible change the view. The image remains in full view, only the +/- signs change inside the magnifying glass icon. A second attempt from the source page does not produce an error.

Example link:

[example1](https://imx.to/i/3dk3n5)

**Comment by Owyn** [comment]
Images don't load for me

![image](https://user-images.githubusercontent.com/1309656/186136734-d2a8f852-208d-404b-8efc-a74fdec1a703.png)


Make sure there are no other userscripts or extensions running on the page

**Comment by BlondFace** [comment]
Try any imx.to picture link ([ex. gallery](https://vipergirls.to/threads/7298801-Freya-Mayer-Lovely-Summer-Dress-50-Photos-4500px-Aug-23-2022)). I use Firefox on several computers under Linux and Windows, the error occurs everywhere with the latest scripts. In one of my browser, the 18.06.2021 version of HandyImage is running, the error does not appear there.

**Comment by Owyn** [comment]
Here, tried via proxy, it seems to work fine in my firefox for all images I tested:
![image](https://user-images.githubusercontent.com/1309656/186146751-aad022f6-3238-4a59-904f-2d7664b86af6.png)
![image](https://user-images.githubusercontent.com/1309656/186146769-d97996f9-230d-4f88-aeca-4a0d08a89c3a.png)

are you sure there are no other extensions or scripts running on the page? does the developer console say anything about errors? (CTRL+SHIFT+J)

**Comment by BlondFace** [comment]
I use Ublock Origin, but even if I turn it off, the error persists. After I see the whole image, nothing happens on further left clicks, I cant zoom into the picture.

On the console these errors are presents after zoom failed on an image:

LoginRecipes: getRecipes: falling back to a synchronous message for: https://imx.to/ [LoginRecipes.jsm:300:16](resource://gre/modules/LoginRecipes.jsm)
sendRemoveListener on closed conduit {e839c3f9-298e-4cd0-99e0-464431cb7c34}.14705968021505 4 [ConduitsChild.jsm:112](resource://gre/modules/ConduitsChild.jsm)

**Comment by BlondFace** [comment]
This is the relevant part of LoginRecipes.jsm file, which sends the message:

if (!Cu.isInAutomation) {
      // this is a blocking call we expect in tests and rarely expect in
      // production, for example when Remote Settings are updated.
      lazy.log.warn(
        "getRecipes: falling back to a synchronous message for:",
        aHost
      );
    }
    recipes = Services.cpmm.sendSyncMessage("PasswordManager:findRecipes", {
      formOrigin: aHost,
    })[0];
    this.cacheRecipes(aHost, win, recipes);

    return recipes;
  },

**Comment by BlondFace** [comment]
So, I disabled Greasemonkey and installed Violentmonkey. HandyImage works without error with Violentmonkey. It appears that
some kind of incompatibility might be causing the problem with the Greasemonkey addon.

**Comment by Owyn** [comment]
Greasemonkey is not supported, it is severely outdated and abandoned by everyone project. 

I'd suggest TamperMonkey
