### ISSUE TITLE
fix imgur.com

### ISSUE THREAD

**Issue by zubrRB** [Owyn/HandyImage#494]
A `.webp` preview opens instead of the original `.jpeg`: https://imgur.com/a/1HWehOP

<details><summary>Screenshot:</summary>

![webp](https://user-images.githubusercontent.com/50718960/194704621-cf9e5168-7b5f-4e25-bb04-378f52d4d7dd.png)
![jpeg](https://user-images.githubusercontent.com/50718960/194704628-a8324e9f-6935-45f8-9aa2-e687c07efe30.png)
</details><br/>

**Comment by Owyn** [comment]
fixed

**Comment by zubrRB** [comment]
It doesn't work for me in Chrome either through AdGuard or Tampermonkey 4.18.0.

**Comment by Owyn** [comment]
doesn't work how? I tested it exactly in chrome with uBlock, cuz in firefox it was originally working fine

**Comment by zubrRB** [comment]
Does not show the original image. Just a normal preview page.

**Comment by Owyn** [comment]
how about now?

**Comment by zubrRB** [comment]
In Firefox it initially worked and works, but not in Chrome.

**Comment by zubrRB** [comment]
It only got worse in Chrome: it used to show at least something, but now it doesn’t.

<details><summary>in Chrome:</summary>

![chrome](https://user-images.githubusercontent.com/50718960/194728867-b4743498-cd10-42fa-9d0d-dd9f7e0fcb6e.png)
</details><br/>

**Comment by Owyn** [comment]
my chrome: 
![изображение](https://user-images.githubusercontent.com/1309656/194729334-d6f23437-58d5-437f-aa72-3126aee60a66.png)

see if browser console says anything from the script (Control + Shift + J), 

and right click -> inspect element on the image to see its html, for me it's this:
![изображение](https://user-images.githubusercontent.com/1309656/194729420-3acfb0f3-84b0-4b28-b136-85b458753a56.png)

**Comment by zubrRB** [comment]
> and right click -> inspect element

The script fires as soon as I try to execute this combination.

**Comment by Owyn** [comment]
Now should work quicker in chrome

**Comment by zubrRB** [comment]
Yes, it works great now.

**Comment by zubrRB** [comment]
Doesn't matter `.jpeg` or `.jpg`?

**Comment by zubrRB** [comment]
It just originally gave `.jpeg`, and now `.jpg` . Although the size is the same.
