### ISSUE TITLE
Enabling "Open images directly with browser" crashes Firefox on some websites

### ISSUE THREAD

**Issue by selimsumlu** [Owyn/HandyImage#513]
I'm on Firefox Nightly 111.0a1 (2023-02-12) and Tampermonkey.

I've always been using HandyImage with "Open images directly with browser" enabled, but lately (a few weeks or so) it's been crashing the Firefox tab on some websites. I've tried disabling all other extensions including uBlock Origin and other userscripts, but it didn't help.

**Example links:**

- https://www.imagevenue.com/ME160T8M
- https://imagetwist.com (I don't have a SFW full link.)

**Comment by Owyn** [comment]
Well, on stable firefox those two sites work just fine opening images directly

I guess "Nightly" is called that for a reason,
and its users were warned when installing that it might be unstable and gonna crash

Not much I can do about it, thought I have pushed an update which might help it (or not),
It's all up to Firefox Nighty devs to make their browser not crush 🤷🏻‍♂️

**Comment by selimsumlu** [comment]
The update did not help, unfortunately. But thanks for taking a look.
