### ISSUE TITLE
https ver of Pronpic.org

### ISSUE THREAD

**Issue by JustinRoper** [Owyn/HandyImage#514]
Can you possible change this
`// @match		http://*.pronpic.org/*/*` to be this? `// @match		http*://*.pronpic.org/*/*` to allow for the https version to work as well. I have to update it every time locally to get it to work after and update.

**Comment by Owyn** [comment]
You could've just pushed a pull request here instead of changing it locally in the first place 😄 

But is there a reason to keep http variant? It redirects me to https in both browsers
