### ISSUE TITLE
Fix pixiv

### ISSUE THREAD

**Issue by ForcedToRock** [Owyn/HandyImage#516]
Just kicks you to a 403 forbidden page as of the last update.
https://www.pixiv.net/en/artworks/105442889

**Comment by Owyn** [comment]
Works fine for me, check that there are no other "privacy" extensions active and that 'open images directly" option is turned off as it should be

**Comment by ForcedToRock** [comment]
How do I disable "open images directly?"

**Comment by zubrRB** [comment]
Hotkey `P` \ menu item in (tamper\grease)monkey icon - open configuration menu.
