### ISSUE TITLE
[fix] imagetwist

### ISSUE THREAD

**Issue by mjolnir870** [Owyn/HandyImage#518]
**Example links to pages with a single image to fullsize: **
[sample link](https://imagetwist.com/pdxdjwpu8hh5/www.0xxx.ws_BigTitsRoundAsses.23.02.04.Crystal.Chase.XXX.1080p.MP4-WRB.mp4-5.jpg)
[direct link to fullsize](https://img119.imagetwist.com/i/54320/pdxdjwpu8hh5.jpg/www.0xxx.ws_BigTitsRoundAsses.23.02.04.Crystal.Chase.XXX.1080p.MP4-WRB.mp4-5.jpg)
-
This is with `Open images directly with browser` checked in the options. It works rarely, but usually the tab crashes:

![image](https://user-images.githubusercontent.com/35158449/219630146-82d5c98f-523b-4799-8c41-0f00a2ce1f28.png)

**Comment by Owyn** [comment]
> This is with Open images directly with browser checked in the options.

directly means browser is opening the image, not the script, so script isn't even there to do anything. I can't fix the browser. Check "send report" box and wait for browser devs to fix this (hopefully).

You can just disable the option to fix this problem.

**Comment by mjolnir870** [comment]
> You can just disable the option to fix this problem. Why did you even enable it in the first place?

I enabled it because I like viewing the direct image so I can use my own styles for images. 

> directly means browser is opening the image, not the script, so script isn't even there to do anything. I can't fix the browser.
Check "send report" box and wait for browser devs to fix this (hopefully).

Opening the image directly works fine. It's only when it is redirected via this userscript that the tab crashes. That's why I think there is a problem with the userscript. I tested this in an entirely new profile with no other extensions except Tampermonkey and Handy Images.

**Comment by Owyn** [comment]
> I enabled it because I like viewing the direct image so I can use my own styles for images.

what kind of styles?
you can use any custom code to do anything or add styles via "custom js" option in the userscript as well

anyway, if your browser is crashing you should at least mention what it is and its version
(and it's a nightly(beta) version - crashes are to be expected...)

**Comment by mjolnir870** [comment]
Tampermonkey v4.19.6177
Firefox Dev 111.0b1 (64-bit)

This has been happening since Firefox 110, but I didn't report it because it was very intermittent. Now it is constant.

**Comment by mjolnir870** [comment]
seems this was a related issue #513

**Comment by Owyn** [comment]
I don't even know why I added that option and now it's bringing trouble. it would be logical to just get rid of it all together...

but here's the last try to fix it before that.

**Comment by Owyn** [comment]
I guess the fix didn't help?

**Comment by mjolnir870** [comment]
Just tested and tabs haven't crashed yet, so seems like it's working. Before the fix the tab crashed every single time.

**Comment by selimsumlu** [comment]
I can confirm that it seems to be working now.

> You can just disable the option to fix this problem. Why did you even enable it in the first place?
@Owyn Obviously you deserve to know the reason why some of us enable that option. I enable it because of the difference in DPI scaling.

I've set Windows DPI scaling to 125% and Firefox honors that setting, so I see 25% bigger images when "Open images directly with browser" is enabled. If not enabled, HandyImage displays them without scaling, thus producing smaller images than my liking.

**Comment by Owyn** [comment]
@selimsumlu 
that's intentional to show original images, 
since I myself also have 125% windows scaling and images become blurry when overly enlarged for no reason 

and when I want them to get bigger - I just resize it with left\middle mouse click
(I have option to fit `Smaller than window` to screen size by default btw)

weird 🤔

**Comment by selimsumlu** [comment]
I understand that's a personal preference. In my case, I prefer scaling all of them and accept the fact that they will become blurry. I believe that still makes them more enjoyable on my 27" screen and I don't need to get closer to the screen to view details. So thank you for providing that option.
