### ISSUE TITLE
"Open images directly with browser" no longer functioning

### ISSUE THREAD

**Issue by Monk18** [Owyn/HandyImage#521]
Seems to be universal, across all sites. I tried isolating it as the only active extension, so no conflicts.

Thanks,

**Comment by Owyn** [comment]
Browser version?

Thanks,

**Comment by Monk18** [comment]
Thanks Owyn for your prompt response! Love the work you've done here. 
I'm on Chrome Version 110.0.5481.104

**Comment by Owyn** [comment]
Should be fixed now.

btw, why are people using the "direct" option? the whole point of the script is the functionality which that option disables...

**Comment by Monk18** [comment]
For me, it's to pair your script with other extensions that might download all tabs, for example. The way your script opens the image makes it hard for other programs to access. But with "open images directly with browser", it works.

ALSO, if I leave a tab open for too long without that setting, if I try to save file, it'll give me an error of file not found. And I won't even notice until much later when I can't get back to the image. There seems to be some kind of time-out in chrome where it stops being accessible in cache or something

**Comment by Owyn** [comment]
Are you saving the image with CTRL+S or by dragging the image?

**Comment by Monk18** [comment]
CTRL+S or right clicking, both have issues.

Anyway, it's just a lot simpler to open in browser. Here's one vote for keeping the feature!

**Comment by Owyn** [comment]
Well, right clicking has nothing to do with the script 🤷🏻  that's purely on the browser...

if it works - I'll keep it

**Comment by zubrRB** [comment]
@Monk18  You can install the Mouseover Popup Image Viewer userscript. 
When hovering the cursor, it will be enough to press the `d` key to download the image.
https://greasyfork.org/ru/scripts/394820-mouseover-popup-image-viewer

**Comment by Owyn** [comment]
@zubrRB I'm pretty sure that MouseOver uses the exact same `GM_Download` mechanism which is on CTRL+S here, and not some other magic...

**Comment by Monk18** [comment]
I'll check that out. I appreciate it!
