### ISSUE TITLE
[QUESTION / BUG?] Is anybody else getting blank screens while using handy image?

### ISSUE THREAD

**Issue by masterofobzene** [Owyn/HandyImage#522]
I'm getting complete white screens in my firefox when trying to see images in some sites (after clicking the desired image on the site, it follows the link to a blank page and no info is shown). 
A test can be done at https://realbooru.com

**Comment by Owyn** [comment]
works fine for my firefox stable

what is your browser and version? what is browser console saying when that happens? ( ctrl+shift+j )

**Comment by Owyn** [comment]
Just make sure you're using the latest userscript version

because that `Handy Image.user.js:1074:43 Uncaught TypeError: a is undefined` was a short-lived bug which got fixed a day ago

**Comment by Owyn** [comment]
your link `https://realbooru.com/index.php?page=post&s=view&id=713248`
script clicks "Original" button for you and gets the image from there, try clicking it by hand and see what happens on that page.
![image](https://user-images.githubusercontent.com/1309656/220758084-08e67844-24ab-4c4c-9ae2-e7f94ff94947.png)
