### ISSUE TITLE
ADD/FIX 

### ISSUE THREAD

**Issue by najushua** [Owyn/HandyImage#529]
**NSFW -** 
I can't even get to the images, grabbed links from sukebei.nyaa.si

http://imgblaze.net/trgw1dp6t but then redirects to http://pixlev.store/trgw1dp6t
http://imgblaze.net/h1cdr but then redirects to http://pixlev.store/h1cdr

**NSFW -** 
https://imgfrost.net/hmtezs redirects to http://pixlev.store/hmtezs

**Comment by Owyn** [comment]
added

**Comment by jasonhpchu** [comment]
Thank to that information, I've just made the above into a bookmarklet for now:
javascript:(function()%7Bwindow.location %3D "https%3A%2F%2Fpixlev.store" %2B document.location.pathname%3B%7D)()

I'm sure Owyn can just do the same thing in HandyImage to do the same thing.

**Comment by Owyn** [comment]
@jasonhpchu I don't even know what that code is for 🤔 
and why would I add into into HandyImage if HandyImage already shows the image just fine on the pixlev site?

**Comment by najushua** [comment]
The link (http://imgair.net/n8tzofx41) posted by Jasonhpchu I can open and see the image, but the blaze/frost I posted still just sit on the countdown page, if you click continue you get an add

If I go directly to the pixlev page I can click continue and get the image, but I still need to click it wont open it automatically

**Comment by najushua** [comment]
Just downloaded Firefox, with just ublock and HandyImage (through tampermonkey) it works for all links

**Comment by jasonhpchu** [comment]
one thing to note, I always test this via incognito.
I find the site "remembers" stuff.
Like if I had clicked through all those buttons, shown ads/popups.  I found subsequent clicks to other images will go straight through.  Probably something in the cookie.

**Comment by jasonhpchu** [comment]
> > On chrome it doesnt show HandyImage even ran (red icon on tampermonkey).
> 
> That means it didn't...
> 
> Update your HandyImage to the latest version and see if it helps, if it still doesn't help - give the url of the page where it doesn't run and I'll double check here why

was just poking in your code, I didn't see imgfrost and imgblaze on the @match and the switch case.
Maybe that's why Handy didn't launch for @najushua

**Comment by Owyn** [comment]
Yes, there's no code for those since they redirect to pixlev immediately for me in both browsers, 

that's why I asked for the url (one shown in the browser url bar) you get stuck on
