### ISSUE TITLE
Realbooru: change source of image

### ISSUE THREAD

**Issue by masterofobzene** [Owyn/HandyImage#533]
In realbooru, there are a certain big number of images that got their indexes scrambled server-side. Problem starts way down on the index (thousands).
The extension uses the "original" button link to show the image . That link is broken for a lot of older images.

Is there any way to tell the script to open the image directly not by using that "original" link but the source image instead?

**Comment by Owyn** [comment]
but... doesn't original image link contain an image of higher quality?
