### ISSUE TITLE
support for a website

### ISSUE THREAD

**Issue by gabri25ele** [Owyn/HandyImage#534]
You need to add https://i.redd.it/ to the list for the reddit image link.
thanks

**Comment by Owyn** [comment]
that's not how it works.

provide example image page links

**Comment by gabri25ele** [comment]
every simple link of reddit with a image hosted in i.redd.it

example
https://www.reddit.com/r/firefox/comments/13au3nl/i_remade_the_firefox_logo_for_minecrafters/
direct link to image would be
https://i.redd.it/hrxzu58hjfya1.png

see also this
https://www.reddit.com/r/help/comments/12dbmks/some_ireddit_image_links_were_loading_a_new_page/

**Comment by Owyn** [comment]
added

**Comment by gabri25ele** [comment]
thanks

**Comment by gabri25ele** [comment]
seem not work... everytime
example https://i.redd.it/zh3hahh10fza1.jpg

**Comment by Owyn** [comment]
added
