### ISSUE TITLE
support for a website: VSCO

### ISSUE THREAD

**Issue by ryancom16** [Owyn/HandyImage#535]
**Example links to pages with a single image to fullsize: **
https://vsco.co/uumutcaan/media/63ee7dca3e0c3f3e2fc3fe75

Image on Page
https://image-aws-us-west-2.vsco.co/f51d4a/58789644/63ee7dca3e0c3f3e2fc3fe75/960x1437/vsco_021623.jpg
Full Sized Image
https://image-aws-us-west-2.vsco.co/f51d4a/58789644/63ee7dca3e0c3f3e2fc3fe75/vsco_021623.jpg
-

> <div class="MediaImage relative" style="max-width:1368px">
	<div class="MediaBgColorWrapper--withRatio relative" style="padding-top: 149.708%;">
		<img class="disableSave-mobile css-6dp941" src="//im.vsco.co/aws-us-west-2/f51d4a/58789644/63ee7dca3e0c3f3e2fc3fe75/vsco_021623.jpg?w=539.05078125&amp;dpr=1" alt="#vsco #vscocam #vscofilter #car #Presets101"/>
	</div>
</div>

**Comment by Owyn** [comment]
added
