### ISSUE TITLE
[BUG\REQUEST] support for a website: VSCO

### ISSUE THREAD

**Issue by ryancom16** [Owyn/HandyImage#536]
Thanks for the quick update! Just a couple of things I noticed -

1. @match is too specific
https://github.com/Owyn/HandyImage/blob/625906f7e95b59e1e1ef48119c0fac701e0e8eeb/HandyImage.user.js#L899

@match		https://vsco.co/uumutcaan/media/*
Should be updated to:
@match		https://vsco.co/*/media/*
to match all users. 

2. With the change above working, handyimage still loads the reduced size image. 

Take for instance this url
https://vsco.co/erinjimerson/media/63056c17f801bc770d9c9689

The image loaded is 
https://im.vsco.co/aws-us-west-2/cd2696/112238337/63056c17f801bc770d9c9689/vsco_082322.jpg?w=1200
Which redirects to 
https://image-aws-us-west-2.vsco.co/cd2696/112238337/63056c17f801bc770d9c9689/1200x800/vsco_082322.jpg

Ideally, it would remove the url parameters "?w=<number>"
https://im.vsco.co/aws-us-west-2/cd2696/112238337/63056c17f801bc770d9c9689/vsco_082322.jpg
Which resolves to 
https://image-aws-us-west-2.vsco.co/cd2696/112238337/63056c17f801bc770d9c9689/vsco_082322.jpg

Thank you!

**Comment by Owyn** [comment]
> uumutcaan

right 😆 
fixed now.

> reduced size

loads absolutely the same file for me for both https://im.vsco.co/aws-us-west-2/cd2696/112238337/63056c17f801bc770d9c9689/vsco_082322.jpg?w=1200
and
https://image-aws-us-west-2.vsco.co/cd2696/112238337/63056c17f801bc770d9c9689/1200x800/vsco_082322.jpg

![image](https://github.com/Owyn/HandyImage/assets/1309656/c06690a3-b445-4003-8532-edbe1c90d853)

**Comment by ryancom16** [comment]
Thank you, the full size is working perfectly now.
