### ISSUE TITLE
[REQUEST] gettyimages.com

### ISSUE THREAD

**Issue by ixxbxxx** [Owyn/HandyImage#537]
**Example links to pages with a single image to fullsize: **
page:
https://www.gettyimages.com/detail/news-photo/fans-watch-the-action-during-the-round-7-barcelona-feature-news-photo/1495850927

full size image:
https://media.gettyimages.com/id/1495850927/photo/barcelona-feature-race.jpg?s=2048x2048&w=gi&k=20&c=NSAcwTSxlpl4_VCkVpmL-PRsfQOIMzA0WOnfra2OX10=

-

**Comment by Owyn** [comment]
added
