### ISSUE TITLE
support for a website

### ISSUE THREAD

**Issue by AltSanvas** [Owyn/HandyImage#538]
Hey Owyn. I tried adding the image host to the scrip and I got it to work but ran into a problem. No matter what I do I can't get the page to scroll. The image is forced to "home" whenever I scroll using mouse wheel or other keyboard functions. 

The image host in question "https://imgnmh.cfd/i2cyo". 

Perhaps I am inputting it in the wrong case? Thank for the help!
-

**Comment by Owyn** [comment]
Why do you want to scroll the page? is it the page with the image already worked by the script or?
I could know if inputting it into the wrong case is the problem if you specified in which one you did it...

anyway, I have added the host myself, should work now
