### ISSUE TITLE
[Suggestion] - make the icon URL base64

### ISSUE THREAD

**Issue by mayhair** [Owyn/HandyImage#544]
The URL to the extension icon on imgbox will not load, at least in my country (Pakistan). Therefore, when trying to use the script, it returns an error after several seconds.

I propose converting the extension icon to a base64 link so that it is not dependent on an external host for the icon, and similar issues will not occur again.

**Comment by Owyn** [comment]
base64 icon would be very heavy and could slow everything down quite a bit

aren't most image hosts this scripts work with are banned in Pakistan anyway?

does https://cubeupload.com/ work there? I could use it instead

**Comment by mayhair** [comment]
yes, cubeupload is not blocked.

**Comment by Owyn** [comment]
done

**Comment by Owyn** [comment]
Well, now the cubeupload  is blocked in **my** country 
![pain](https://github.com/Owyn/HandyImage/assets/1309656/8556e661-8c63-4320-a2d5-57291c3521e4)

switched to imgbb.com for now
