### ISSUE TITLE
Imagebam constantly reloading/not working in Falkon + GreaseMonkey v.0.9.4 + Handy Image 2023.07.12

### ISSUE THREAD

**Issue by slrslr** [Owyn/HandyImage#547]
Hello,

i am using web browser Falkon with built-in GreaseMonkey extension v.0.9.4 inside which I have Handy Image:
// ==UserScript==
// @name		Handy Image
// @version		2023.07.12

Imagebam is not loading properly. It is stuck and constantly refreshing on the [page](https://www.imagebam.com/view/ME3NWH2) where is Continue to your image kind of message.
After i have disabled Handy image (inside GreaseMonkey) , continued to image and enabled Handy Image again, it started loading images OK. After computer restart, HI is enabled and issue is there again.

**Comment by Owyn** [comment]
Imagebam  was fixed 2 days ago: https://github.com/Owyn/HandyImage/commit/28311ff25644b10214b4b69afe26a7527f2349ae 
make sure you have the latest script version

**Comment by slrslr** [comment]
Thank you for a kind reply. I see that there is a refresh button inside GreaseMonkey window near HandyImage script. So it was updated and after browser restart, no issue, worked.
