### ISSUE TITLE
Shopify

### ISSUE THREAD

**Issue by ixxbxxx** [Owyn/HandyImage#548]
Mind taking a stab at shopify? Here is the official doc on how they rename the files:
https://www.shopify.com/partners/blog/img-url-filter

**Example links to pages with a single image to fullsize: **
https://www.beachbunnyswimwear.com/products/ultrabraid-large-brim-visor-beige?variant=18624689700979

the above URL points to this image: https://www.beachbunnyswimwear.com/cdn/shop/products/UBV022-OSBGE_d4609dab-3b13-455d-9480-708c7a0f1f56_1800x.jpg?v=1678325197

however the original sized image is name is this: https://www.beachbunnyswimwear.com/cdn/shop/products/UBV022-OSBGE_d4609dab-3b13-455d-9480-708c7a0f1f56.jpg?v=1678325197

filenames without the width and/or height and/or size description e.g. large/medium/etc

- 

Thank you!

**Comment by Owyn** [comment]
Do you want me to add support for beachbunnyswimwear.com website? 🤔

**Comment by ixxbxxx** [comment]
I had in mind all Shopify websites but i now realise that your filter is based on domain. I notice that Shopify backends use either cdn.shopify.com or the seller's domain when linking images and i don't suppose you can work with that?

**Comment by Owyn** [comment]
> Shopify backends use either cdn.shopify.com or the seller's domain when linking images and i don't suppose you can work with that?

Indeed, this works with a whitelist of domains to work on, not on every website.

Plus I don't think it would be even a good idea to add something like shop websites - images there are for seeing the goods, not for saving into your gallery lol, if we leave just the image - the price and description would go away - the things people choose by
