### ISSUE TITLE
eksisozluk1923.com

### ISSUE THREAD

**Issue by desdesifre** [Owyn/HandyImage#549]
from
https://eksisozluk1923.com/img/ucz4fzpe
to
https://cdn.eksisozluk1923.com/2023/8/7/u/ucz4fzpe.jpg

**Comment by Owyn** [comment]
I don't think that's an image hosting website 🤔 

if you really want the script to work there - just add a custom rule into your settings, e.g. in firefox: script settings -> user includes and add `https://eksisozluk1923.com/img/*` there - script will now show the biggest image on pages starting with that address
![image](https://github.com/Owyn/HandyImage/assets/1309656/8f7174f2-5751-4f25-bacd-35fdf1297798)
![image](https://github.com/Owyn/HandyImage/assets/1309656/afb115c3-ebf1-4200-a206-be4dc4690764)

**Comment by desdesifre** [comment]
yes this code worked thank you very much.

**Comment by Owyn** [comment]
> so is there a way to hide scroll lock? that is, when I open the page, the scale will appear, but I want it to be full screen when I click with the mouse. What code can I do this with?

try changing script's settings to fit all images to window perhaps for that?
![image](https://github.com/Owyn/HandyImage/assets/1309656/d0cf7382-7592-4dac-8365-08d9fbce69da)

**Comment by desdesifre** [comment]
How can I open the configuration menu? I am using greasemonkey plugin.

**Comment by Owyn** [comment]
Press `P` on keyboard when an image is open or choose "configuration" in the greassmonkey menu when the script is running
