### ISSUE TITLE
fix vipr.im

### ISSUE THREAD

**Issue by 13spacemen** [Owyn/HandyImage#567]
**Example links to pages with a single image to fullsize: **
WARNING NSFW
https://vipr.im/ibjobq5iryf7

it keeps showing "warning-1.png" instead of the image

sometimes it works, and sometimes it doesn't. maybe it's an internet speed thing? but still could you fix this, by blocking opening the non-target image images?
-

**Comment by Owyn** [comment]
not sure how it happens but I've made a change
