### ISSUE TITLE
vipr.im still broken

### ISSUE THREAD

**Issue by 13spacemen** [Owyn/HandyImage#568]
sorry for again same issue
**Example links to pages with a single image to fullsize: **
here is pic of my problem

![Screenshot 2023-11-18 003542](https://github.com/Owyn/HandyImage/assets/46101244/e30d98c6-d5b1-4d14-9817-0562bec4e3d1)

- 

my internet is slow, so HandyImage is showing me these other small pics instead of the target picture (which is much larger in MB)

**Comment by Owyn** [comment]
Size is irrelevant if the website is supported by the script itself

What does your browser console say? (right click -> inspect -> console)

**Comment by 13spacemen** [comment]
currently i am not getting the problem, but i know it will happen sometime in future
i will reopen and post chrome console output when it happens again
i think this issue has something to do with: internet speed, or CloudFlare

**Comment by Owyn** [comment]
or maybe your adblock letting ads through, since chrome forbade adblocks or smth (I use Firefox)

**Comment by Owyn** [comment]
should be good now

**Comment by Owyn** [comment]
ok
