### ISSUE TITLE
Imageblaze.net >> picvvvd.sbs

### ISSUE THREAD

**Issue by katsuya82** [Owyn/HandyImage#569]
**Example links to pages with a single image to fullsize: **

HandyImage used to work on imgblaze.net, somehow it's not listed supported? is it possible to add it back?

*warning* 18+ pic
http://imgblaze.net/qlebyym

It seems the imgblaze.net will jump to picvvvd.sbs and then numerous click and new ad windows to go to image.

**Comment by Owyn** [comment]
added
