### ISSUE TITLE
imx.to: save image

### ISSUE THREAD

**Issue by tevans180** [Owyn/HandyImage#582]
I'm using Vivaldi 6.5 with tampermonkey 5.0.1 and HandyImage 2024.02.16. 

When opening an image https://imx.to/i/1qdeva I am unable to save the image unless I re-open the image in a separate tab. This results in the image https://i001.imx.to/i/2018/04/09/1qdeva.png opening with a specified hostname and direct path. 

I'm unsure how to do additional troubleshooting. 

Can you reproduce? And if not, how can I get further detail?

**Comment by Owyn** [comment]
Saved fine for me on my chrome, 
try opening browser console (Shift + CTRL + J) and see error message there

**Comment by Owyn** [comment]
also changing download mode in TM settings might help 
![318044976-2419da42-9a5c-4200-bb9c-aa02e0616632](https://github.com/Owyn/HandyImage/assets/1309656/cc771629-3492-4d7d-9359-91beca87ff11)
