### ISSUE TITLE
ibb.co is broken

### ISSUE THREAD

**Issue by goonis** [Owyn/HandyImage#589]
**Example links to pages with a single image to fullsize: https://ibb.co/SVX41NW**

Chrome 126, Tampermonkey 5.1.1, Handy Image 2024.06.04 gives empty page, after pressing "Handy Image/Reload page normally" on Tampermonkey menu or disabling Handy Image in Tampermonkey settings page loads ok.

**Comment by Owyn** [comment]
Works fine for me 
![image](https://github.com/Owyn/HandyImage/assets/1309656/0f1fd777-febd-4bc9-a1a5-19d88f80ce61)

Make sure other scripts or extensions aren't blocking the image (.e.g - adBlocker)

**Comment by goonis** [comment]
Ok, problem was located, it's Tampermonkey setting "Inject mode", it was in "Instant" mode (because one of the scripts I use require it), after changing this setting to "Normal" (or "Default") Handy Image works ok.
