### ISSUE TITLE
 Fix imagetwist.com

### ISSUE THREAD

**Issue by swathigrate** [Owyn/HandyImage#592]
Fix  imagetwist 
Actually I am using soul browser 1.4.30 

[[**Example links to pages with a single image to fullsize: **

- https://imagetwist.com/5gjsimrzzmoc/RESBOBC.MOV_snapshot_02.02__2024.08.13_12.45.40_.jpg

**Comment by Owyn** [comment]
Works fine for me in both normal popular browser engines
![image](https://github.com/user-attachments/assets/78e76f0a-d5b9-45df-9f04-84cc881b8f1d)

Try disabling other extensions\scripts\changing the browser

**Comment by zubrRB** [comment]
Soul Browser this is a browser for Android.

**Comment by swathigrate** [comment]
> Soul Browser this is a browser for Android.

Yes  sir .....

**Comment by swathigrate** [comment]
> Works fine for me in both top 2 popular browsers ![image](https://private-user-images.githubusercontent.com/1309656/357385737-78e76f0a-d5b9-45df-9f04-84cc881b8f1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MTA3MzMsIm5iZiI6MTcyMzYxMDQzMywicGF0aCI6Ii8xMzA5NjU2LzM1NzM4NTczNy03OGU3NmYwYS1kNWI5LTQ1ZGYtOWYwNC04NGNjODgxYjhmMWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTRUMDQ0MDMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTA5ZmIxZTA2YzU4NDU4ZWViZTZlYjZiYzU0YjBkZGUxZGRjZTA4ZGM5NWZkZjdkOTNlZmY0ZGRjNjhlZWI3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wjZx1I1x6piLSoUwjllOnNYmmo8wbBzYtD4KQUARdaM)
> 
> Try disabling other extensions\scripts\changing the browser
Sir ... Not opening in  full image in soul browser .....I think it is soul browser issue

**Comment by Owyn** [comment]
> I think it is soul browser issue

Perhaps, it might be missing some important functional so the script can't work

I've heard it worked fine in mobile firefox browser at least

**Comment by swathigrate** [comment]
> > I think it is soul browser issue
> 
> Perhaps, it might be missing some important functional so the script can't work
> 
> I've heard it worked fine in mobile firefox browser at least

Yeah it's working fine in remaining  Android browsers like frefox,kiwi  etc.... but small bug
Actually images are not opening full screen mode ... Showing some contents up and down sides .....

**Comment by Owyn** [comment]
> Actually images are not opening full screen mode ... Showing some contents up and down sides .....

To keep the aspect mode of the Image I presume... You could select not to and "fill to window" instead of "fit" **in the script's configuration** which would make it full screen, but some parts of the image would get cut off (obviously)
