### ISSUE TITLE
Imgur albums behavior with multiple images

### ISSUE THREAD

**Issue by stevekh2** [Owyn/HandyImage#594]
**Example links to pages with a single image to fullsize: https://imgur.com/a/costco-coupon-book-aug-28-sept-22-2025-94NqXXA**

Hi @Owyn, this is a great tool for most sites, however, I am consistently only having the first image of an Imgur album load. Is this intended and if so, is there a way to add exceptions (via regex, a UI panel, or something similar) to Imgur albums to not load the script? I think a gallery option would work the best here, but that definitely is extra and is out of scope here.

Edit: The reload function would work here to load the image without the script active if the URL was preserved. Whenever I reload the page, it bumps me to the main Imgur homepage as it looks like the URL is stripped completely.

**Comment by Owyn** [comment]
added an exclude for /a/ addresses, hope that helps

**Comment by Owyn** [comment]
> is there a way to add exceptions (via regex, a UI panel, or something similar)

there is https://github.com/Owyn/HandyImage/blob/master/Tutorial%20-%20disable%20script%20for%20specific%20websites.md

it's not just for the websites, you can later edit the exclude url in the script manager's settings
