### ISSUE TITLE
pimpandhost.com (NSFW)

### ISSUE THREAD

**Issue by swathigrate** [Owyn/HandyImage#596]
**Example links to pages with a single image to fullsize: **

- 
https://pimpandhost.com/image/256946786
https://pimpandhost.com/image/270680717
When opening pics showing count down timer of 20 sec

Soul browser

**Comment by Owyn** [comment]
works fine both in firefox and chrome, I can't really support all the existing browsers out there - perhaps it's missing something important or just configured that way

you could check browser console to see if there are any errors there
